from _language_edit_helpers import apply

apply("site/pl/index.html", [
    ("Xiaomi Mi Dash Cam MJXCJLY01BY — poprawiony plik APK dla Androida 15/16 i HyperOS", "Xiaomi Mi Dash Cam MJXCJLY01BY — APK dla Androida 15/16 i HyperOS"),
    ("Działający plik APK dla Xiaomi Mi Dash Cam MJXCJLY01BY w wersji EU, przeznaczony dla nowych wersji Androida i HyperOS. Wi-Fi, podgląd na żywo, nagrania, pobieranie i odtwarzanie sprawdzono z prawdziwą kamerą.", "Zmodyfikowany APK dla europejskiej Xiaomi Mi Dash Cam MJXCJLY01BY (EU), przeznaczony do współczesnych wersji Androida i HyperOS. Połączenie Wi-Fi, podgląd na żywo, nagrania, pobieranie i odtwarzanie sprawdzono z fizyczną kamerą."),
    ("Nie. To niezależny projekt utrzymujący użyteczność porzuconego oprogramowania. Nazwy Xiaomi, Mi, Mijia i 70mai należą do ich właścicieli.", "Nie. To niezależny projekt zgodności dla aplikacji, której producent już nie rozwija. Nazwy Xiaomi, Mi, Mijia i 70mai należą do ich właścicieli."),
    ("Tak, w przetestowanej konfiguracji. Wersja 2.0.0 przeszła pełny test z fizyczną kamerą na Poco F6 z Androidem 16 i HyperOS 3.", "Tak, na przetestowanej konfiguracji. Wersja 2.0.0 przeszła pełny test z fizyczną kamerą na Poco F6 z Androidem 16 i HyperOS 3."),
    ("SHA-256 pozwala potwierdzić, że pobrany APK jest dokładnie plikiem opublikowanym w repozytorium. Android wymaga też podpisu APK; ta wersja jest podpisana kluczem projektu, a nie oryginalnym kluczem Xiaomi.", "SHA-256 pozwala sprawdzić, czy pobrany APK jest identyczny z plikiem opublikowanym przez projekt. Android wymaga również podpisu APK; ta wersja jest podpisana kluczem projektu, a nie oryginalnym kluczem Xiaomi."),
    ("Zgodność sprawdzona na prawdziwej kamerze", "Sprawdzono z fizyczną kamerą"),
    ("Przywróć <span class=\"accent\">Mi Dash Cam</span> do działania.", "Używaj <span class=\"accent\">Mi Dash Cam</span> na współczesnym Androidzie."),
    ("Oryginalna europejska aplikacja od lat nie jest już rozwijana. Ten poprawiony plik APK pozwala ponownie używać Xiaomi Mi Dash Cam <code>MJXCJLY01BY</code> z nowymi wersjami Androida — bez konieczności logowania się na konto Mi.", "Xiaomi nie rozwija już oryginalnej europejskiej aplikacji. Ta wersja przywraca lokalną obsługę Xiaomi Mi Dash Cam <code>MJXCJLY01BY</code> na współczesnych wersjach Androida bez logowania do konta Mi."),
    ("Przetestowano z fizyczną kamerą", "Testy z fizyczną kamerą"),
    ("Lokalne Wi-Fi · bez chmury", "Lokalne Wi-Fi · bez usług chmurowych"),
    ("Udokumentowany zakres testów", "Udokumentowane testy"),
    ("Nowe i starsze procesory", "Obsługa ARM64 i ARMv7"),
    ("Suma SHA-256 opublikowana", "SHA-256 opublikowany"),
    ("Możliwość weryfikacji pliku", "Sprawdź pobrany plik"),
    ("Najpierw sprawdź kamerę", "Sprawdź numer modelu"),
    ("Jeden model. Bez zgadywania.", "Przed instalacją upewnij się, że to właściwa kamera."),
    ("Xiaomi używało bardzo podobnych nazw dla różnych rejestratorów. Przed instalacją porównaj kod modelu z etykietą urządzenia.", "Xiaomi stosowało bardzo podobne nazwy dla różnych rejestratorów. Przed instalacją sprawdź kod modelu na obudowie kamery."),
    ("Co naprawiono", "Co naprawia ta wersja"),
    ("Sprzęt działa. Problemem była aplikacja.", "Poprawki dla współczesnych wersji Androida."),
    ("Zmiany skupiają się na funkcjach, które faktycznie przestały działać na nowych telefonach.", "Zmiany dotyczą funkcji, które przestały działać prawidłowo na nowszych telefonach."),
    ("Bez zależności od konta Mi", "Lokalnie, bez konta Mi"),
    ("Aplikacja uruchamia się z kontem „Offline” i działa lokalnie, bez korzystania z przestarzałego mechanizmu logowania Xiaomi.", "Aplikacja uruchamia się z profilem „Offline” i działa lokalnie, bez przestarzałego mechanizmu logowania Xiaomi."),
    ("Dowody zamiast deklaracji opartych wyłącznie na emulatorze.", "Testy z fizyczną kamerą."),
    ("Ten sam plik APK z wydania przetestowano z prawdziwą kamerą w wersji EU. Testy innych wersji Androida i ich ograniczenia opisano w repozytorium.", "Opublikowaną wersję 2.0.0 przetestowano z fizyczną kamerą w wersji EU. Wyniki testów innych wersji Androida oraz ich ograniczenia opisano w repozytorium."),
    ("Cztery kroki do podglądu na żywo.", "Instalacja w czterech krokach."),
    ("Pobierz sprawdzone wydanie", "Pobierz wersję 2.0.0"),
    ("Wersja 2.0.0 jest aktualną stabilną kompilacją. SHA-256 pozwala sprawdzić, czy pobrany APK jest identyczny z opublikowanym plikiem.", "Wersja 2.0.0 jest aktualnym stabilnym wydaniem. Za pomocą SHA-256 możesz sprawdzić, czy pobrany APK jest identyczny z opublikowanym plikiem."),
    ("Nieoficjalny projekt zgodności, który przedłuża życie sprawnego sprzętu. Kod źródłowy, wyniki testów i sumy kontrolne są publiczne na GitHubie.", "Nieoficjalny projekt zgodności dla modelu MJXCJLY01BY. Kod źródłowy, wyniki testów i sumy kontrolne są dostępne na GitHubie."),
])
