from _language_edit_helpers import apply

apply("site/de/index.html", [
    ("Xiaomi Mi Dash Cam MJXCJLY01BY — APK-Fix für Android 15/16 und HyperOS", "Xiaomi Mi Dash Cam MJXCJLY01BY — APK für Android 15/16 und HyperOS"),
    ("Funktionierende APK für die europäische Xiaomi Mi Dash Cam MJXCJLY01BY (EU) auf aktuellen Android-Versionen und HyperOS. WLAN, Livebild, Aufnahmen, Downloads und Wiedergabe wurden mit einer echten Kamera getestet.", "Angepasste APK für die europäische Xiaomi Mi Dash Cam MJXCJLY01BY auf aktuellen Android-Versionen und HyperOS. WLAN-Verbindung, Livebild, Aufnahmen, Downloads und Wiedergabe wurden mit einer echten Kamera getestet."),
    ("Nein. Dies ist ein unabhängiges Erhaltungs- und Kompatibilitätsprojekt für nicht mehr gepflegte Begleitsoftware. Xiaomi, Mi, Mijia und 70mai sind Marken ihrer jeweiligen Inhaber.", "Nein. Dies ist ein unabhängiges Kompatibilitätsprojekt für eine Begleit-App, die nicht mehr gepflegt wird. Xiaomi, Mi, Mijia und 70mai sind Marken ihrer jeweiligen Inhaber."),
    ("Kompatibilität mit echter Kamera geprüft", "Mit einer echten Kamera getestet"),
    ("Bring deine <span class=\"accent\">Mi Dash Cam</span> wieder zum Laufen.", "Nutze deine <span class=\"accent\">Mi Dash Cam</span> wieder mit aktuellem Android."),
    ("Die ursprüngliche europäische App wird seit Jahren nicht mehr unterstützt. Diese angepasste APK-Datei macht die Xiaomi Mi Dash Cam <code>MJXCJLY01BY</code> wieder mit aktuellen Android-Versionen nutzbar — ganz ohne Mi-Konto.", "Die ursprüngliche europäische App wird nicht mehr gepflegt. Diese angepasste Version macht die Xiaomi Mi Dash Cam <code>MJXCJLY01BY</code> wieder mit aktuellen Android-Versionen nutzbar, ohne dass ein Mi-Konto erforderlich ist."),
    (">Fixes<", ">Korrekturen<"),
    ("Lokales WLAN · keine Cloud nötig", "Lokales WLAN · ohne Cloud-Dienst"),
    ("Dokumentierter Testumfang", "Dokumentierte Tests"),
    ("Moderne und ältere CPUs", "ARM64 und ARMv7"),
    ("Prüfbare Dateiintegrität", "Download lässt sich prüfen"),
    ("Zuerst das Kameramodell prüfen", "Modellnummer prüfen"),
    ("Ein Modell. Keine Vermutungen.", "Vor der Installation das Kameramodell prüfen."),
    ("Xiaomi hat sehr ähnliche Produktnamen für verschiedene Dashcams verwendet. Prüfe vor der Installation den Modellcode auf dem Gerät.", "Xiaomi hat für verschiedene Dashcams sehr ähnliche Produktnamen verwendet. Prüfe vor der Installation den Modellcode auf der Kamera."),
    ("Was repariert wurde", "Was diese Version behebt"),
    ("Die Hardware funktioniert. Die App war das Problem.", "Kompatibilitätskorrekturen für aktuelle Android-Versionen."),
    ("Die Änderungen konzentrieren sich auf die Funktionen, die auf aktuellen Smartphones tatsächlich ausgefallen sind.", "Die Änderungen betreffen Funktionen, die auf neueren Smartphones nicht mehr zuverlässig arbeiteten."),
    ("Kein Mi-Konto erforderlich", "Lokale Nutzung ohne Mi-Konto"),
    ("Die App startet mit einem Offline-Konto und arbeitet lokal, ohne vom veralteten Xiaomi-Login abhängig zu sein.", "Die App startet mit einem Offline-Konto und arbeitet lokal, ohne den veralteten Xiaomi-Anmeldevorgang zu benötigen."),
    ("Nachweise aus echter Hardware statt nur aus dem Emulator.", "Mit der echten Kamera getestet."),
    ("Die veröffentlichte APK-Datei wurde mit einer echten Kamera in der EU-Version getestet. Tests anderer Android-Versionen und ihre Grenzen sind im Repository dokumentiert.", "Die veröffentlichte Version 2.0.0 wurde mit einer echten Kamera in der EU-Version getestet. Weitere Android-Versionen wurden separat geprüft; Umfang und Grenzen dieser Tests sind im Repository dokumentiert."),
    ("Ihr Browser kann diese MP4-Datei nicht abspielen. Öffnen Sie das Originalvideo auf GitHub.", "Dein Browser kann diese MP4-Datei nicht abspielen. Öffne das Originalvideo auf GitHub."),
    ("Vier Schritte bis zum Livebild.", "Installation in vier Schritten."),
    ("Getestete Version herunterladen", "Version 2.0.0 herunterladen"),
    ("Version 2.0.0 ist die aktuelle stabile Kompatibilitätsversion. Mit SHA-256 lässt sich prüfen, ob die heruntergeladene Datei exakt dem veröffentlichten APK entspricht.", "Version 2.0.0 ist die aktuelle stabile Kompatibilitätsversion. Mit SHA-256 kannst du prüfen, ob die heruntergeladene Datei dem veröffentlichten APK entspricht."),
    ("Inoffizielles Kompatibilitätsprojekt zur weiteren Nutzung funktionsfähiger Hardware. Quellcode, Testergebnisse und Prüfsummen sind öffentlich auf GitHub verfügbar.", "Inoffizielles Kompatibilitätsprojekt für die MJXCJLY01BY. Quellcode, Testergebnisse und Prüfsummen sind auf GitHub verfügbar."),
])
